version: '3'
#https://www.digitalocean.com/community/tutorials/how-to-containerize-a-laravel-application-for-development-with-docker-compose-on-ubuntu-18-04-ru
services:
  #MySQL Service https://hub.docker.com/_/mysql
  db:
    image: mysql:8.0.12
    #command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  #Nginx Service https://hub.docker.com/_/nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ${APP_PATH_DIR}:${APP_PATH_CONTAINER}
      - ${FOLDER_LOG_PATH}/nginx/:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app

  #PHP Service
  app:
    image: app
    container_name: app
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_DIR}:${APP_PATH_CONTAINER}
      - ${FOLDER_LOG_PATH}/app/:/var/log/php
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
#      - ./docker/php-fpm/pool.d/www.conf:/usr/local/etc/php-fpm.d/custom.conf
    links:
      - db

#todo
# does not work(docker bug)
#   env_file:
#   - ./docker/app/.env